-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "BiomarkerType" ADD VALUE 'HEART_RATE_VARIABILITY_RMSSD';
ALTER TYPE "BiomarkerType" ADD VALUE 'INSULIN_DELIVERY';
ALTER TYPE "BiomarkerType" ADD VALUE 'MINDFULNESS';
ALTER TYPE "BiomarkerType" ADD VALUE 'SLEEP_IN_BED';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_ENERGY_CONSUMED';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_CARBS_CONSUMED';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_PROTEIN_CONSUMED';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_FATS_CONSUMED';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_FIBER';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_SUGAR';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_CAFFEINE';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_FAT_SATURATED';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_FAT_MONOUNSATURATED';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_FAT_POLYUNSATURATED';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_CHOLESTEROL';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_VITAMIN_A';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_VITAMIN_C';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_VITAMIN_D';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_VITAMIN_E';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_VITAMIN_K';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_THIAMIN';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_RIBOFLAVIN';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_NIACIN';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_PANTOTHENIC_ACID';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_VITAMIN_B6';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_BIOTIN';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_VITAMIN_B12';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_FOLATE';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_CALCIUM';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_IRON';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_MAGNESIUM';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_PHOSPHORUS';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_POTASSIUM';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_SODIUM';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_ZINC';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_CHROMIUM';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_COPPER';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_IODINE';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_MANGANESE';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_MOLYBDENUM';
ALTER TYPE "BiomarkerType" ADD VALUE 'DIETARY_SELENIUM';
