// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Nx6Lt-f6vc5vvo7gFB1j3jiNU5ps7tE',
    appId: '1:12654915458:web:e4020fe9d2d6e06eb9a99b',
    messagingSenderId: '12654915458',
    projectId: 'mystasis-a6b7b',
    authDomain: 'mystasis-a6b7b.firebaseapp.com',
    storageBucket: 'mystasis-a6b7b.firebasestorage.app',
    measurementId: 'G-SG471SX4TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDLDZT5hF0yFxDHhoJ2e1YuEaLKeQsP8k',
    appId: '1:12654915458:android:11ade2427fe5672fb9a99b',
    messagingSenderId: '12654915458',
    projectId: 'mystasis-a6b7b',
    storageBucket: 'mystasis-a6b7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfoN2RGNtmWIyNTPJxJCDHbb5GYLgIrdQ',
    appId: '1:12654915458:ios:cdefba04c687c606b9a99b',
    messagingSenderId: '12654915458',
    projectId: 'mystasis-a6b7b',
    storageBucket: 'mystasis-a6b7b.firebasestorage.app',
    iosBundleId: 'com.example.mystasis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfoN2RGNtmWIyNTPJxJCDHbb5GYLgIrdQ',
    appId: '1:12654915458:ios:cdefba04c687c606b9a99b',
    messagingSenderId: '12654915458',
    projectId: 'mystasis-a6b7b',
    storageBucket: 'mystasis-a6b7b.firebasestorage.app',
    iosBundleId: 'com.example.mystasis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2Nx6Lt-f6vc5vvo7gFB1j3jiNU5ps7tE',
    appId: '1:12654915458:web:77bd097a77a9cca5b9a99b',
    messagingSenderId: '12654915458',
    projectId: 'mystasis-a6b7b',
    authDomain: 'mystasis-a6b7b.firebaseapp.com',
    storageBucket: 'mystasis-a6b7b.firebasestorage.app',
    measurementId: 'G-5242NTLGVR',
  );
}
